# Generated by Django 5.1.6 on 2025-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Name', models.CharField(max_length=50)),
                ('Model_Name', models.CharField(max_length=50)),
                ('Car_Colour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.IntegerField()),
                ('Valid_Card_Date', models.DateField(auto_now=True)),
                ('Expired_Card_Date', models.DateField()),
                ('CV_Number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Contact', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=8)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Personal_Informations',
            },
        ),
    ]
