# Generated by Django 5.1.6 on 2025-07-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
    ]
